### ISSUE TITLE
Output for the Pre-trained onxx Model was 1KB 

### ISSUE THREAD

**Issue by ali7569392725** [Crystalsound/FRN#3]
Tried Inferencing the already existing model with 48KHz sample audio lossy file , the output length is expected to match with input length , but output was generating 1KB
![image](https://github.com/Crystalsound/FRN/assets/36409054/2399ac7d-b121-4c36-b155-30bb4530f058)

**Comment by vietanh125** [comment]
Can you try this [demo](https://huggingface.co/spaces/anhnv125/FRN) and see if it generates output correctly?

**Comment by ali7569392725** [comment]
Demo is working fine but while I'm running the inference script , output is not properly generating ,Following is the command and modified my output & input paths in config.

"python inference_onnx.py --onnx_path lightning_logs/version_0/checkpoints/frn.onnx"

**Comment by vietanh125** [comment]
Hi, sorry for the late reply.

Probably the onnx model in the repo is different from one in the HF space. Can you try using the one in HF space? [https://huggingface.co/spaces/anhnv125/FRN/blob/main/lightning_logs/version_0/checkpoints/frn.onnx](https://huggingface.co/spaces/anhnv125/FRN/blob/main/lightning_logs/version_0/checkpoints/frn.onnx)
